# Generated by Django 4.1.5 on 2023-01-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturls',
            name='url_visited',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
