# Generated by Django 4.1.5 on 2023-01-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_shorturls_url_visited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturls',
            name='shorten_url',
            field=models.CharField(max_length=10),
        ),
    ]
