# Generated by Django 4.1.5 on 2023-01-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0003_alter_shorturls_shorten_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturls',
            name='url',
        ),
    ]
