# Generated by Django 4.1.5 on 2023-01-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0004_remove_shorturls_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturls',
            name='url',
            field=models.URLField(default=None, max_length=510),
            preserve_default=False,
        ),
    ]
