# Generated by Django 4.1.5 on 2023-01-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0005_shorturls_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturls',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shorturls',
            name='shorten_url',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
