# Generated by Django 4.1.5 on 2023-01-14 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0006_shorturls_count_alter_shorturls_shorten_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturls',
            name='url_visited',
        ),
    ]
